language: python
python:
  - "2.7"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  # - "pypy"
# command to install dependencies
install:
  - sudo apt -y install libgdal-dev  # dependencies of dgal
#  - export CPLUS_INCLUDE_PATH=/usr/include/gdal
#  - export C_INCLUDE_PATH=/usr/include/gdal
  # manually build and install gdal
  - pip install GDAL==$(gdal-config --version | awk -F'[.]' '{print $1"."$2}') --global-option=build_ext --global-option="-I/usr/include/gdal/"
  - pip install .
  - pip install -r requirements.txt
# command to run tests
#script: nosetests
script: py.test tests/core

