dist: trusty
sudo: required  # use VM instead of docker

language: python
python:
  - "2.7"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  # - "pypy"

cache:
  pip: true  # make cache for pip dependencies
  directories:
    - cache  # cached files

env:
  - MATPLOTLIB_VERSION=2.1.0 QT_VERSION=4
  - MATPLOTLIB_VERSION=2.0.2 QT_VERSION=4
  - MATPLOTLIB_VERSION=1.5.3 QT_VERSION=4

before_install:
  - sudo apt update -qq
#  - sudo apt -y install -qq libgdal-dev=2.2.2  # dependencies of dgal
  # build gdal from source as the one on ubuntu trusty is out-of-date
  - chmod +x ./bin/install_libgdal.sh && ./bin/install_libgdal.sh
  - export CPLUS_INCLUDE_PATH=/usr/include/gdal
  - export C_INCLUDE_PATH=/usr/include/gdal
  - export LD_LIBRARY_PATH="/usr/local/gdal/lib:$LD_LIBRARY_PATH"
  - export PATH="/usr/local/gdal/bin:$PATH"

# command to install dependencies
install:
  # manually build and install gdal
#  - pip install GDAL==$(gdal-config --version | awk -F'[.]' '{print $1"."$2}') --global-option=build_ext --global-option="-I/usr/include/gdal/"
  - sudo apt install python-qt$QT_VERSION
  - pip install -q matplotlib==$MATPLOTLIB_VERSION
  - pip install -q -r requirements.txt

before_script:
  - pip install pytest-xdist  # add xdist for distributing tests
  - pip freeze  # show installed packages
#  # install mtpy2 in dev mode
#  - pip install .

script:
  - py.test -n 4 tests/core
  - py.test tests/imaging
  - py.test -n 4 tests/modeling
  - ./bin/travis_set_display.sh  # enable display on travis
  - py.test tests/SmartMT

matrix:
  fast_finish: true
  allow_failures:
    - env: MATPLOTLIB_VERSION=2.0.2 QT_VERSION=4
    - env: MATPLOTLIB_VERSION=1.5.3 QT_VERSION=4

