dist: trusty
sudo: required  # use VM instead of docker

language: python
python:
  - "2.7"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  # - "pypy"

cache:
  pip: true  # make cache for pip dependencies
  directories:
    - builds  # cached files

install: true  # skip default install step which would be called before the prepare cache stage

env:
  global:
    - COVERALLS_PARALLEL=true
  matrix:
#    - MATPLOTLIB_VERSION=2.1.0 QT_VERSION=4
    - MATPLOTLIB_VERSION=2.0.2 QT_VERSION=5
    - MATPLOTLIB_VERSION=2.1.0 QT_VERSION=5
    - MATPLOTLIB_VERSION=2.0.2 QT_VERSION=4
    - MATPLOTLIB_VERSION=1.5.3 QT_VERSION=5

stages:
  - name: prepare cache
  - test
  - name: GUI Test

jobs:
  include:
    - stage: prepare cache  # run saperate job to build dependencies to avoid 50 min timeout on travis
      script: true # place holder, the before_Script will run anyway
      env:
        - MATPLOTLIB_VERSION=2.0.2 QT_VERSION=5
    - stage: prepare cache
      script: true
      env:
        - MATPLOTLIB_VERSION=2.1.0 QT_VERSION=5
    - stage: prepare cache
      script: true
      env:
        - MATPLOTLIB_VERSION=2.0.2 QT_VERSION=4
    - stage: prepare cache
      script: true
      env:
        - MATPLOTLIB_VERSION=1.5.3 QT_VERSION=5
#    - stage: test
    - stage: GUI Test
      script: . ./bin/travis-test-gui.sh
      env:
        - MATPLOTLIB_VERSION=2.0.2 QT_VERSION=5
    - stage: GUI Test
      script: . ./bin/travis-test-gui.sh
      env:
        - MATPLOTLIB_VERSION=2.0.2 QT_VERSION=4
#    - stage: deploy
  allow_failures:
    - env: MATPLOTLIB_VERSION=2.1.0 QT_VERSION=5
    - env: MATPLOTLIB_VERSION=2.0.2 QT_VERSION=4
    - env: MATPLOTLIB_VERSION=1.5.3 QT_VERSION=5

before_script:
  - chmod -vR +x ./bin/* && . ./bin/travis-setup-env.sh  

script: # testing stages, will run only in testing stages
  - MTPY_TEST_COMPARE_IMAGE=False py.test -v -n4 --dist=loadscope --cov=mtpy --cov-report= tests --ignore=tests/SmartMT

after_success:
  - coveralls

matrix:
  fast_finish: true
  allow_failures:
    - env: MATPLOTLIB_VERSION=2.1.0 QT_VERSION=5
    - env: MATPLOTLIB_VERSION=2.0.2 QT_VERSION=4
    - env: MATPLOTLIB_VERSION=1.5.3 QT_VERSION=5

notifications:
  webhooks: https://coveralls.io/webhook?repo_token=GsdWzB3YUFjVVGCESQode5GgbnUINLZr2
