dist: trusty
sudo: required  # use VM instead of docker

language: python
python:
  - "2.7"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  # - "pypy"

cache:
  pip: true  # make cache for pip dependencies
  directories:
    - builds  # cached files

env:
  global:
    - COVERALLS_PARALLEL=true

before_install:
  - chmod -vR +x ./bin/*

stages:
  - name: prepare cache
  - test

jobs:
  include:
    - stage: prepare cache
      matrix:
        - MATPLOTLIB_VERSION=2.1.0 QT_VERSION=5
        - MATPLOTLIB_VERSION=2.0.2 QT_VERSION=4
        - MATPLOTLIB_VERSION=2.0.2 QT_VERSION=5
        - MATPLOTLIB_VERSION=1.5.3 QT_VERSION=5
      script: ./bin/travis-setup-env
    - stage: test
      matrix:
        - MATPLOTLIB_VERSION=2.1.0 QT_VERSION=5
        - MATPLOTLIB_VERSION=2.0.2 QT_VERSION=4
        - MATPLOTLIB_VERSION=2.0.2 QT_VERSION=5
        - MATPLOTLIB_VERSION=1.5.3 QT_VERSION=5
      script: py.test -v -n 4 --dist=loadscope --cov=mtpy --cov-report= tests/analysis
      script: py.test -v -n 4 --dist=loadscope --cov=mtpy --cov-report= tests/core
      script: MTPY_TEST_COMPARE_IMAGE=False py.test -v -n 4 --dist=loadscope --cov=mtpy --cov-report= tests/imaging
      script: py.test -v -n 4 --dist=loadscope --cov=mtpy --cov-report= tests/modeling
      script: py.test -v -n 4 --dist=loadscope --cov=mtpy --cov-report= tests/utils
      script: #  test gui
        - "export DISPLAY=:99.0"  # enable display on travis
        - "sh -e /etc/init.d/xvfb start"
        - sleep 3 # give xvfb some time to start
        - py.test -v -n 4 --dist=loadscope --cov=mtpy --cov-report= tests/SmartMT
#    - stage: deploy

after_success:
  - coveralls

matrix:
  fast_finish: true
  allow_failures:
    - env: MATPLOTLIB_VERSION=2.1.0 QT_VERSION=5
    - env: MATPLOTLIB_VERSION=2.0.2 QT_VERSION=4
    - env: MATPLOTLIB_VERSION=1.5.3 QT_VERSION=5

notifications:
  #webhooks: https://coveralls.io/webhook?repo_token=cAPLOTdLM6wuguwHgdUsBqtDprbhVZfRp
