version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
        datefmt: "%Y-%m-%dT%H:%M:%S"

handlers:
    console: # screen display print out
        class: logging.StreamHandler
        level: INFO
        formatter: simple
        stream: ext://sys.stdout

loggers:
    my_module:
        level: DEBUG
        handlers: [console]
        propagate: no

    __main__:
        level: INFO 
        handlers: [console]
        propagate: no

root:
    level: ERROR 
    #handlers: [console, info_file_handler, error_file_handler]
    handlers: [console, ]
